Cargo.toml
README.md
examples/turn_based_game.rs
src/component.rs
src/resource.rs
tests/determinism.rs

Due to `TypePath` requirements for reflection, `EntropyComponent`/`GlobalEntropy` must have custom `TypePath` implementations in order to still be able to wrap around `RngCore` structs without requiring upstream RNGs/`rand` crates to pull in bevy and implement `TypePath` themselves. This PR allows for the shim to continue to exist without forcing this requirement to upstream RNGs, nor forcing the crate to not impose `TypePath` trait constraints onto the generics, forcing all users to need to newtype their RNGs just to provide the `TypePath` trait.

feat: Custom TypePath impl for component/resource

---

Cargo.toml
README.md
bevy_prng/Cargo.toml
bevy_prng/LICENSE-APACHE
bevy_prng/LICENSE-MIT
bevy_prng/README.md
bevy_prng/src/lib.rs
examples/turn_based_game.rs
src/component.rs
src/lib.rs
src/plugin.rs
src/resource.rs
src/thread_local_entropy.rs
src/traits.rs
tests/determinism.rs

WIP for next version of `bevy_rand`, with a new support crate for `rand` PRNG newtypes that will plug into `bevy_rand` components/resources.

feat: bevy_prng crate & stable TypePath wrappers

---

.github/workflows/ci.yml
Cargo.toml
MIGRATIONS.md
README.md
bevy_prng/Cargo.toml
bevy_prng/README.md
bevy_prng/src/lib.rs
examples/turn_based_game.rs
src/component.rs
src/lib.rs
src/plugin.rs
src/prelude.rs
src/resource.rs
src/thread_local_entropy.rs
src/traits.rs
tests/determinism.rs

The Forking Refactor, where instead of `From` implementations (which did allow for control over how one created new PRNG instances), various traits to provide forking methods have been provided instead to simplify the process of forking from a `GlobalEntropy` source to `EntropyComponent`, and also for `EntropyComponent` to `EntropyComponent`. The refactor also covers cases where forking between different algorithm types, as well as forking the inner PRNG instances of `GlobalEntropy`/`EntropyComponent`.
- `fork_rng()` - This is the simplest method, forks with the same PRNG between original and forked instances. I'm more partial to shortening to `fork` however, as that is seen elsewhere in `fastrand` and `turborand`.
- `fork_as()` - This method allows forking to a specified PRNG algorithm, …

refactor: Forking via traits

---

Cargo.toml
README.md
bevy_prng/src/newtype.rs
src/thread_local_entropy.rs

The original implementation of `ThreadLocalEntropy` was based on `rand`'s `ThreadRng`, making a few changes to not require reseeding or forking protection in order to assume cases more in-line with game application usage. However, as a result, it picked up the issues with the original implementation, such as leaking memory if the destructors for `ThreadLocalEntropy` didn't run.
This new implementation does away with cloning an `Rc` reference, instead opting for keeping the references within the `LocalKey::with` closure, avoiding any reference counting. The `Rc` prevents premature freeing during thread-local destructors, while keeping the ref inside the `with` closure ensures that we never end up in a situation where we might have a ref counted instance that never gets cleaned up.
This …

feat: Better thread local access

---

Cargo.toml
MIGRATIONS.md
README.md
tests/determinism.rs

Updates to the latest version of the `wyrand` dependency. Because it is a breaking change output-wise, `bevy_rand` is being updated to a new major version to maintain semver guarantees.

chore: Update to latest wyrand version

---

Cargo.toml
src/lib.rs
src/plugin.rs
src/prelude.rs
src/resource.rs
src/seed.rs
tests/determinism.rs

Adds a `GlobalRngSeed` resource with reflection support, mainly for allowing users to track/monitor the initial starting seed/state for a given `GlobalEntropy`. This should allow for users to also write systems that can force a `GlobalEntropy` resource to reseed.
Closes #18

feat: add GlobalRngSeed resource for tracking initial state/seed

---

Cargo.toml
src/seed.rs
tests/determinism.rs

In order to have any sort of reseeding mechanisms between `GlobalRngSeed` and `GlobalEntropy`, one needs to be able to update `GlobalRngSeed` after initialisation.
Best not to forget including important methods such as this in the future. Includes test to ensure such a scenario can occur.

feat: Add set_seed method to GlobalRngSeed

---

Cargo.toml
MIGRATIONS.md
README.md
src/component.rs
src/lib.rs
src/plugin.rs
src/prelude.rs
src/resource.rs
src/seed.rs
src/traits.rs
tests/integration/determinism.rs
tests/integration/mod.rs
tests/integration/reseeding.rs
tests/suite.rs

This PR adds a `RngSeed` component type for containing the seed value of an `EntropyComponent`, plus establishing the relationship between the two components so that adding or overwriting a `RngSeed` component to an entity will add/overwrite an `EntropyComponent` of the same PRNG type. This is implemented using component hooks and will be automatically initialised when using the plugin to register entropy source types.
With this, I've also added extra forking traits to enable PRNG sources to fork to a seed component, whether of the same or different algorithm type.
I've also restructured the integration tests to build into a single test binary, but have separate modules for clarity purpose's sake. This should allow the integration test suite to grow considerably without needing to …

feat: RngSeed & ForkableSeed traits

---

MIGRATIONS.md
bevy_prng/src/lib.rs
src/component.rs
src/plugin.rs
src/prelude.rs
src/resource.rs
src/seed.rs
src/traits.rs
tests/integration/determinism.rs
tests/integration/reseeding.rs

Yeet `GlobalRngSeed` and instead roll the initial seed info into `GlobalEntropy`, so that reseeding will automatically reinitialise the RNG and to better associate/track the initial seed for reflection purposes.

refactor(GlobalRng): Merge seed resource with rng source

---

bevy_prng/src/lib.rs
src/component.rs
src/prelude.rs
src/resource.rs
src/traits.rs
tests/integration/reseeding.rs

Adds a missing corollary to the other `Forkable...` traits, but for outputting a forked seed type directly (instead of a component). Also adds observer tests on how reseeding via observers might occur, including reseeding related entities.
Included with the PR are a bunch of small fixes as well.

feat: Add ForkableInnerSeed trait, observer tests, fixes

---

Cargo.toml
README.md
bevy_prng/README.md
bevy_prng/src/lib.rs
bevy_prng/src/newtype.rs
bevy_prng/src/xoshiro.rs
src/component.rs
src/plugin.rs
src/prelude.rs
src/resource.rs
src/seed.rs
tests/integration/reseeding.rs
tutorial/01-choosing-prng.md

Now we're ready for the 0.15 release!
Some notable weirdness to this bump: `Reflect` has been split into `PartialReflect` and `Reflect`. TL;DR - `PartialReflect` just means that you can access the fields of the represented type. `Reflect` on the other hand is an actual instance of the represented type. (or at least something like that). Regardless, `ReflectDeserializer` now spits out `PartialReflect` types, which means we need to do more work to extract the correct types.

Bump Bevy to 0.15.0-rc.3.

---

README.md
bevy_prng/README.md
bevy_prng/src/newtype.rs
bevy_prng/src/xoshiro.rs
src/prelude.rs
src/seed.rs
tutorial/01-choosing-prng.md

After #27 removed the 512 bit variants of Xoshiro due to them being broken by default, this PR attempts to re-enable those variants by remote-reflecting the needed seed wrapper `Seed512`. The implementation here should allow for the 512 bit variants to be accepted by the trait constraints of `SeedableEntropySource`, while allowing the underlying wrapped structs to still be compatible to each other.

refactor: Reenable 512 bit variants of Xoshiro with remote reflected Seed512

---

.github/workflows/ci.yml
README.md

Remove old deprecated cargo checks and default to using clippy instead of `cargo check` so that lints and warnings can be upgraded to errors in CI.

feat: Use clippy instead of check for better lint enforcement

---

src/observers.rs
src/seed.rs
tests/integration/reseeding.rs

Make use of `Single/Populated` system params to tidy things up. Might need to figure out whether populated not being populated means it won't run/error is a problem or not.

refactor: Tidy up observer code with single/populated system params

---

src/observers.rs
src/seed.rs

Updates to latest bevy main changes, makes `RngSeed` an immutable component and also updates to observer `target` method

feat: Immutable RngSeed, update observer target

---

Cargo.toml
MIGRATIONS.md
README.md
bevy_prng/src/chacha.rs
bevy_prng/src/lib.rs
bevy_prng/src/newtype.rs
bevy_prng/src/pcg.rs
bevy_prng/src/wyrand.rs
bevy_prng/src/xoshiro.rs
examples/turn_based_game.rs
src/component.rs
src/observers.rs
src/plugin.rs
src/prelude.rs
src/resource.rs
src/seed.rs
src/traits.rs
tests/integration/determinism.rs
tests/integration/reseeding.rs
tutorial/03-components-forking.md

Renaming the component from `EntropyComponent` to just `Entropy` since it is a bit redundant otherwise. `SeedableEntropySource` is now just `EntropySource` since again, the trait constraints are enough to determine what is a valid source so no need to have a long name.

refactor: Rename components/traits to shorter names

---

.github/workflows/ci.yml
src/seed.rs
src/traits.rs

Closes #37
Fix does what it says on the tin. Also as an extra, ensure this doesn't happen again with a CI check. Might have to do a setup to go and test as many feature permutations as possible, but that's for another PR and time.

fix: Correct variable naming in from_entropy method

---

.github/workflows/ci.yml
Cargo.toml
README.md
bevy_prng/Cargo.toml
bevy_prng/src/lib.rs

Closes #36 if successful.
Changing the feature setup for `bevy_rand` and `bevy_prng` to have better defaults, as well as removing the assumption for WASM builds being Web ones (leaving it to the application to define this, as this will be the incoming requirement changes for `getrandom`)

fix: Better feature testing and default features

---

Cargo.toml
MIGRATIONS.md
bevy_prng/src/chacha.rs
bevy_prng/src/lib.rs
bevy_prng/src/pcg.rs
bevy_prng/src/wyrand.rs
bevy_prng/src/xoshiro.rs
examples/turn_based_game.rs
src/commands.rs
src/component.rs
src/global.rs
src/lib.rs
src/observers.rs
src/params.rs
src/plugin.rs
src/prelude.rs
src/seed.rs
tests/integration/determinism.rs
tests/integration/mod.rs
tests/integration/reseeding.rs
tests/suite.rs
tutorial/02-basic-usage.md
tutorial/04-seeding.md
tutorial/05-observer-driven-reseeding.md

This PR will represent a major refactor of aspects of `bevy_rand` with the observers feature, making use of relations to simplify some of the internal code and also redoing the API for interacting with the observers to make use of a more streamlined commands API.
The work here will be destined for the next version of Bevy, due to being dependent on a number of features currently only present on the `main` branch.
Goals of this PR:

refactor: Relations, Command API and plugin-reorg

---

Cargo.lock
src/commands.rs
src/component.rs
src/global.rs
src/observers.rs
src/params.rs
src/prelude.rs
src/seed.rs
src/thread_local_entropy.rs
src/traits.rs
tests/integration/extension.rs
tests/suite.rs

Implements two new extensions traits, `ForkRngExt` and `ForkSeedExt` on `&mut World`, to help improve ergonomics around accessing a global source from exclusive systems.
Might bikeshed the trait names and intentions further.
Closes #47

feat: Extension traits for forking

---

Cargo.lock
Cargo.toml
README.md
bevy_prng/README.md
src/commands.rs
src/component.rs

Branch for readying Bevy v0.16. You can use this branch to test the RC version with:
```toml
bevy_rand = { git = "https://github.com/Bluefinger/bevy_rand", branch = "prepare-v0.16", package = "bevy_rand" }
```

feat: Prepare for Bevy v0.16

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
MIGRATIONS.md
README.md
bevy_prng/Cargo.toml
bevy_prng/README.md
bevy_prng/src/chacha.rs
bevy_prng/src/lib.rs
bevy_prng/src/newtype.rs
bevy_prng/src/pcg.rs
bevy_prng/src/wyrand.rs
bevy_prng/src/xoshiro.rs
src/commands.rs
src/component.rs
src/global.rs
src/lib.rs
src/observers.rs
src/params.rs
src/plugin.rs
src/prelude.rs
src/seed.rs
src/traits.rs
tutorial/01-choosing-prng.md

A small refactor of trait constraints and requirements across `bevy_prng` and `bevy_rand`, to clean up some implementations across the board and to enable optional `bevy_reflect` support, so to improve the `no_std` support story (since reflection imposes quite a bit of `alloc` overhead, which while fine for more capable hardware, is a bit much for more resource constrained platforms such as embedded boards and old console hardware like the GBA).
This is a breaking change which will require a new major version due to differences in what deps are enabled when default features is false. Otherwise, this will be a straightforward upgrade.

feat: Optional bevy_reflect for better `no_std` support

---

src/component.rs

This seems to have been forgotten, since `Entropy<R>` does implement `Default`.

Reflect Default for Entropy<R>
